In [25]:
import numpy as np
import numpy.matlib

In [12]:
cat1 = np.array([[1,3],[5,7],[9,11]])
cat2 = np.array([[2,4],[6,8],[10,12]])
np.multiply(cat1,cat2).sum()

322

In [6]:
np_matrix.sum()

4

In [16]:
cat1 = np.array([1, 2, 3])
print(cat1)

[1 2 3]


In [31]:
result_matrix =  np.array([cat1,]*3) - np.array([cat1,] * 3).transpose()

In [32]:
result_matrix[result_matrix < 0] = 0

In [33]:
result_matrix

array([[0, 1, 2],
       [0, 0, 1],
       [0, 0, 0]])

In [30]:
np.matlib.repmat(cat1,2,1).transpose()

array([[1, 1],
       [2, 2],
       [3, 3]])